Get events support subcription
Lin1404/Timebook pull request #15
Opened 2023-06-07 20:18 UTC by Lin1404

2023-06-09 15:18 UTC, HaofengLiang requested changes

2023-06-09 15:18 UTC, HaofengLiang commented on src/main/java/com/timebook/timebook/service/EventService.java
> +    public Event post(Event requestEvent) {
Maybe just call it save.

2023-06-09 15:18 UTC, HaofengLiang commented on src/main/java/com/timebook/timebook/service/EventService.java
> +        result.put("Subscription", subscription);
Using all lower case key may reduce some amount of issues.

2023-06-09 15:18 UTC, HaofengLiang commented on src/main/java/com/timebook/timebook/service/EventService.java
> +    public Predicate<Event> datefilter(String period, String date) {
Maybe name it to createDateFilter. (This is actually a kind of factory pattern.)

2023-06-09 15:18 UTC, HaofengLiang commented on src/main/java/com/timebook/timebook/service/EventService.java
> +        for (int i = 0; i < subscritionList.size(); i++) {
nit: Use foreach loop or foreach method might reduce lines and make it easier to read.

2023-06-09 17:28 UTC, Lin1404 commented on src/main/java/com/timebook/timebook/service/EventService.java
> +    public Event post(Event requestEvent) {
Because this API included 'add' and 'update' events

2023-06-12 14:38 UTC, HaofengLiang approved these changes

2023-06-12 14:39 UTC, merged